# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1500)),
                ('serves', models.IntegerField()),
                ('prep_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('cook_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('ingredients', models.CharField(max_length=1500)),
                ('instructions', models.CharField(max_length=1500)),
                ('suits', models.CharField(max_length=1500)),
                ('calories', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('fat', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('saturates', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('sugars', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('fibre', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('salt', models.DecimalField(decimal_places=2, default='', max_digits=5)),
                ('created_date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('published_date', models.DateField(blank=True, verbose_name='Conversation Date')),
            ],
        ),
    ]
